name: env
channels:
  - conda-forge
dependencies:
  - python=3.6.1
  - numpy
  - pip
  - pip:
    - pandas
    - matplotlib
    - azureml-core
    - azureml-defaults
    - lightgbm
    - mlflow
    - azureml-mlflow
    - numpy
    - scikit-learn
    - fasttext
    - gensim
    - pytorch
    - seaborn
    - nltk
    - keras
    - tensorflow
    - lime
    - transformers
    - pycuda
    - csv